### ISSUE TITLE
watch list dropdown super slow for large environment

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.Dashboard#24]
Im finding that when using the watchlist porlet, access to the drop down list is very slow..we have alot of objects in our zenoss deployment but the speed, so far is an order of magitude slower than the old watch list drop down.

What im doing is adding a device or container to the drop list of an existing watch list.

**Comment by dougsyer** [comment]
it may be because its now also allowing you to add networks as well as devices to it...i havent looked at how the call to the catalog/device list has changed yet.

**Comment by jhanson** [comment]
If someone has a lot of network objects then the slowdown will be caused by waking up all the objects in this method: 
https://github.com/zenoss/ZenPacks.zenoss.Dashboard/blob/develop/ZenPacks/zenoss/Dashboard/facades.py#L127
A better approach would be to infer the full organizer name from the path of the brain.

**Comment by dougsyer** [comment]
I have a dev system with a zenpack set to monkeypatch the dashboard zenpack if you need help testing i plan to move this to a clone of our full production instance in the next couple of weeks.

**Comment by dougsyer** [comment]
adding a watch list to the network isnt a requirement for us, there could be a checkbox to search those in addition to devices and sub organizers or to exclusively search those in my opinion.

Im having other issues trying to add individual devices via cut/paste of the device id where somtimes it works and sometimes im getting an refresh message.   I tried to set the portlet refresh high but it seems to be still happening.

so to test i open a watch list and paste in a device id/title when i do that i will get a "needs a refresh message" and the device doesnt add.  other times it works.

**Comment by dougsyer** [comment]
![refresh](https://cloud.githubusercontent.com/assets/1815352/13118156/ea96d8aa-d570-11e5-92da-2889ad3f9691.JPG)

**Comment by dougsyer** [comment]
looks like the above happens if you paste a device into the drop down list and hit add before it finds the device you pasted in.
I can get it to consistently happen by pasting in the device name and hitting add after a couple of seconds.  if i paste the device name in and wait until it has found the device it seems to work.

**Comment by dougsyer** [comment]
yeah if i paste a device name in that doesnt exist or isnt indexed i get the stale data warning..
